name: build and push code
on:
  push:
    branches: [ "ci_test" ]
jobs:
  git-push:
    name: build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: deploy
          FOLDER: build
