name: build and push code
on:
  push:
    branches: [ "ci_test2" ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: deploy
        run: |
          chmod +x ~/build_deploy.sh
          sudo ~/build_deploy.sh